### ISSUE TITLE
Missing output file(s) `*_hits.txt` expected by process `makeKmerDB (1)`

### ISSUE THREAD

**Issue by dagkesamanskaya** [droeatumn/kpi#3]
Dear Dave Roe, 

I am struggling with this issue, the input fastqs are present. I believe something wrong goes in the kmc_tools part as it doesn't generate a file which is used in the next substep

./main.nf --id FND00001567 --raw /kpi/input/ --output /kpi/output/

N E X T F L O W  ~  version 22.04.3
Launching `./main.nf` [happy_austin] DSL1 - revision: b4644491c2
executor >  local (1)
[78/788d62] process > makeKmerDB (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > db2Locus       -
[-        ] process > hapInterp      -
Error executing process > 'makeKmerDB (1)'

Caused by:
  Missing output file(s) `*_hits.txt` expected by process `makeKmerDB (1)`

Command executed:

  export JAVA_OPTS='-Xmx200g'
  ./probeFastqsKMC.groovy -d FND00001567 -p input  -o . -w . 2> probeFastqsKMC.log
  ./filterMarkersKMC2.groovy -d . -p markers -o . -w . 2> filterMarkersKMC2.log		
  find . -type f -size 0 | xargs rm # remove 0 length files, especially hits.txt files

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /kpi/work/78/788d62945d51b8b2fa782cb5b64a42

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by droeatumn** [comment]
This usually happens when it can't find sufficient KIR reads in the input.
Could you share the fastq files with me so I can recreate it? I'm at roex0050@umn.edu.
Too much depth (>255x) can also be a problem. If that might be the case, then downsampling the reads before inputting to KPI will solve the issue.

**Comment by droeatumn** [comment]
Also, if you're not using the docker container, you need to add '--nocontainer'.

Is this still an issue?

**Comment by droeatumn** [comment]
I have time to debug this with you, if you like.
For starters, there should be some log files in the work folder. If you could attach those, it would help.

**Comment by droeatumn** [comment]
Feel free to get back to me if/when you'd like to work on this.
There is a new version of KPI. I don't expect it will fix your issue, but I recommend you try and send me the logs if it doesn't.
