### ISSUE TITLE
Not able to go beyond makeKmerDB, please help

### ISSUE THREAD

**Issue by archaemenes** [droeatumn/kpi#5]
./main.nf --id id1 --raw ./input --output ./output
N E X T F L O W  ~  version 22.10.7
Launching `./main.nf` [sad_poitras] DSL1 - revision: bb0bf38dd6
executor >  local (1)
[3b/c1ca2c] process > makeKmerDB (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > db2Locus       -
[-        ] process > hapInterp      -
Error executing process > 'makeKmerDB (1)'

Caused by:
  Process `makeKmerDB (1)` terminated with an error exit status (1)

Command executed:

  export JAVA_OPTS='-Xmx200g'
  ./probeFastqsKMC.groovy -d id1 -p input -t fq  -o . -w . 2> probeFastqsKMC.log
  ./filterMarkersKMC2.groovy -d . -p markers -o . -w . 2> filterMarkersKMC2.log		
  find . -type f -size 0 | xargs rm # remove 0 length files, especially hits.txt files

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /home/archaemenes/software/KPI/kpi/work/3b/c1ca2c39110386c48b83daad7c34e1

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by droeatpm** [comment]
What is the input? For example, short-read whole genome sequences? If so, do you have at least 13 CPU, 16G RAM total and 100G temp disk space? Or, are you extracting sequences from an alignment?
Also, if you could share the input file(s) with me, I'd be happy to take a look. You can email the details to me.

**Comment by archaemenes** [comment]
./main.nf --id id1 --raw input --output output

I am just trying out the examples given
The system configurations are satisfied 16 CPUs  32G RAM 500G disk space

**Comment by archaemenes** [comment]
SOLVED!

worked after adding the following to $HOME/.nextflow/config

docker.enabled = true
docker.fixOwnership = true
